// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 顶层
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Global        *Global                `protobuf:"bytes,3,opt,name=global,proto3" json:"global,omitempty"`
	Log           *Log                   `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetGlobal() *Global {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

// ============== Server ==============
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Asynq         *Server_Asynq          `protobuf:"bytes,2,opt,name=asynq,proto3" json:"asynq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetAsynq() *Server_Asynq {
	if x != nil {
		return x.Asynq
	}
	return nil
}

// ============== Data ==============
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	DatabaseList  []*Data_Database       `protobuf:"bytes,3,rep,name=database_list,json=databaseList,proto3" json:"database_list,omitempty"` // YAML: data.databaseList
	RedisList     []*Data_Redis          `protobuf:"bytes,4,rep,name=redis_list,json=redisList,proto3" json:"redis_list,omitempty"`          // YAML: data.redisList
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetDatabaseList() []*Data_Database {
	if x != nil {
		return x.DatabaseList
	}
	return nil
}

func (x *Data) GetRedisList() []*Data_Redis {
	if x != nil {
		return x.RedisList
	}
	return nil
}

// ============== Global ==============
type Global struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rsa           *Global_RSA            `protobuf:"bytes,1,opt,name=rsa,proto3" json:"rsa,omitempty"`   // YAML: global.rsa
	Game          *Global_Game           `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"` // YAML: global.game
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Global) Reset() {
	*x = Global{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global) ProtoMessage() {}

func (x *Global) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global.ProtoReflect.Descriptor instead.
func (*Global) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Global) GetRsa() *Global_RSA {
	if x != nil {
		return x.Rsa
	}
	return nil
}

func (x *Global) GetGame() *Global_Game {
	if x != nil {
		return x.Game
	}
	return nil
}

// ============== Log ==============
type Log struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`                                            // 日志级别: debug, info, warn, error (默认: info)
	VerboseTaskLog bool                   `protobuf:"varint,2,opt,name=verbose_task_log,json=verboseTaskLog,proto3" json:"verbose_task_log,omitempty"` // 是否显示详细的定时任务日志 (默认: false)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetVerboseTaskLog() bool {
	if x != nil {
		return x.VerboseTaskLog
	}
	return false
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // 对应 YAML: server.http.timeout: "1s"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_Asynq struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Addr          string                     `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                     `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                      `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	Subscriber    []*Server_Asynq_Subscriber `protobuf:"bytes,4,rep,name=subscriber,proto3" json:"subscriber,omitempty"` // YAML: server.asynq.subscriber
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_Asynq) Reset() {
	*x = Server_Asynq{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Asynq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Asynq) ProtoMessage() {}

func (x *Server_Asynq) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Asynq.ProtoReflect.Descriptor instead.
func (*Server_Asynq) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_Asynq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_Asynq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Server_Asynq) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Server_Asynq) GetSubscriber() []*Server_Asynq_Subscriber {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

type Server_Asynq_Subscriber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schedule      string                 `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_Asynq_Subscriber) Reset() {
	*x = Server_Asynq_Subscriber{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Asynq_Subscriber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Asynq_Subscriber) ProtoMessage() {}

func (x *Server_Asynq_Subscriber) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Asynq_Subscriber.ProtoReflect.Descriptor instead.
func (*Server_Asynq_Subscriber) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *Server_Asynq_Subscriber) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server_Asynq_Subscriber) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"` // 仅在 database_list 里使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	NqDb          int32                  `protobuf:"varint,4,opt,name=nq_db,json=nqDb,proto3" json:"nq_db,omitempty"` // YAML: data.redis.nq_db
	Alias         string                 `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`            // 仅在 redis_list 里使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetNqDb() int32 {
	if x != nil {
		return x.NqDb
	}
	return 0
}

func (x *Data_Redis) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Global_RSA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        string                 `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private       string                 `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Global_RSA) Reset() {
	*x = Global_RSA{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global_RSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global_RSA) ProtoMessage() {}

func (x *Global_RSA) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global_RSA.ProtoReflect.Descriptor instead.
func (*Global_RSA) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Global_RSA) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *Global_RSA) GetPrivate() string {
	if x != nil {
		return x.Private
	}
	return ""
}

type Global_Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaza         *Global_Game_Plaza     `protobuf:"bytes,1,opt,name=plaza,proto3" json:"plaza,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Global_Game) Reset() {
	*x = Global_Game{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global_Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global_Game) ProtoMessage() {}

func (x *Global_Game) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global_Game.ProtoReflect.Descriptor instead.
func (*Global_Game) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Global_Game) GetPlaza() *Global_Game_Plaza {
	if x != nil {
		return x.Plaza
	}
	return nil
}

type Global_Game_Plaza struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Server82         string                 `protobuf:"bytes,1,opt,name=server82,proto3" json:"server82,omitempty"`                                          // YAML: global.game.plaza.server82
	Server87Host     string                 `protobuf:"bytes,2,opt,name=server87_host,json=server87Host,proto3" json:"server87_host,omitempty"`              // YAML: global.game.plaza.server87Host
	KeepaliveSeconds int32                  `protobuf:"varint,3,opt,name=keepalive_seconds,json=keepaliveSeconds,proto3" json:"keepalive_seconds,omitempty"` // YAML: global.game.plaza.keepalive_seconds
	AutoReconnect    bool                   `protobuf:"varint,4,opt,name=auto_reconnect,json=autoReconnect,proto3" json:"auto_reconnect,omitempty"`          // YAML: global.game.plaza.auto_reconnect
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Global_Game_Plaza) Reset() {
	*x = Global_Game_Plaza{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global_Game_Plaza) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global_Game_Plaza) ProtoMessage() {}

func (x *Global_Game_Plaza) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global_Game_Plaza.ProtoReflect.Descriptor instead.
func (*Global_Game_Plaza) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1, 0}
}

func (x *Global_Game_Plaza) GetServer82() string {
	if x != nil {
		return x.Server82
	}
	return ""
}

func (x *Global_Game_Plaza) GetServer87Host() string {
	if x != nil {
		return x.Server87Host
	}
	return ""
}

func (x *Global_Game_Plaza) GetKeepaliveSeconds() int32 {
	if x != nil {
		return x.KeepaliveSeconds
	}
	return 0
}

func (x *Global_Game_Plaza) GetAutoReconnect() bool {
	if x != nil {
		return x.AutoReconnect
	}
	return false
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xac\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12*\n" +
	"\x06global\x18\x03 \x01(\v2\x12.kratos.api.GlobalR\x06global\x12!\n" +
	"\x03log\x18\x04 \x01(\v2\x0f.kratos.api.LogR\x03log\"\x83\x03\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12.\n" +
	"\x05asynq\x18\x02 \x01(\v2\x18.kratos.api.Server.AsynqR\x05asynq\x1aO\n" +
	"\x04HTTP\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1a\xca\x01\n" +
	"\x05Asynq\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12C\n" +
	"\n" +
	"subscriber\x18\x04 \x03(\v2#.kratos.api.Server.Asynq.SubscriberR\n" +
	"subscriber\x1a<\n" +
	"\n" +
	"Subscriber\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x02 \x01(\tR\bschedule\"\xa8\x03\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12>\n" +
	"\rdatabase_list\x18\x03 \x03(\v2\x19.kratos.api.Data.DatabaseR\fdatabaseList\x125\n" +
	"\n" +
	"redis_list\x18\x04 \x03(\v2\x16.kratos.api.Data.RedisR\tredisList\x1aP\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x1ar\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12\x13\n" +
	"\x05nq_db\x18\x04 \x01(\x05R\x04nqDb\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\"\xf5\x02\n" +
	"\x06Global\x12(\n" +
	"\x03rsa\x18\x01 \x01(\v2\x16.kratos.api.Global.RSAR\x03rsa\x12+\n" +
	"\x04game\x18\x02 \x01(\v2\x17.kratos.api.Global.GameR\x04game\x1a7\n" +
	"\x03RSA\x12\x16\n" +
	"\x06public\x18\x01 \x01(\tR\x06public\x12\x18\n" +
	"\aprivate\x18\x02 \x01(\tR\aprivate\x1a\xda\x01\n" +
	"\x04Game\x123\n" +
	"\x05plaza\x18\x01 \x01(\v2\x1d.kratos.api.Global.Game.PlazaR\x05plaza\x1a\x9c\x01\n" +
	"\x05Plaza\x12\x1a\n" +
	"\bserver82\x18\x01 \x01(\tR\bserver82\x12#\n" +
	"\rserver87_host\x18\x02 \x01(\tR\fserver87Host\x12+\n" +
	"\x11keepalive_seconds\x18\x03 \x01(\x05R\x10keepaliveSeconds\x12%\n" +
	"\x0eauto_reconnect\x18\x04 \x01(\bR\rautoReconnect\"E\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12(\n" +
	"\x10verbose_task_log\x18\x02 \x01(\bR\x0everboseTaskLogB!Z\x1fbattle-tiles/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),               // 0: kratos.api.Bootstrap
	(*Server)(nil),                  // 1: kratos.api.Server
	(*Data)(nil),                    // 2: kratos.api.Data
	(*Global)(nil),                  // 3: kratos.api.Global
	(*Log)(nil),                     // 4: kratos.api.Log
	(*Server_HTTP)(nil),             // 5: kratos.api.Server.HTTP
	(*Server_Asynq)(nil),            // 6: kratos.api.Server.Asynq
	(*Server_Asynq_Subscriber)(nil), // 7: kratos.api.Server.Asynq.Subscriber
	(*Data_Database)(nil),           // 8: kratos.api.Data.Database
	(*Data_Redis)(nil),              // 9: kratos.api.Data.Redis
	(*Global_RSA)(nil),              // 10: kratos.api.Global.RSA
	(*Global_Game)(nil),             // 11: kratos.api.Global.Game
	(*Global_Game_Plaza)(nil),       // 12: kratos.api.Global.Game.Plaza
	(*durationpb.Duration)(nil),     // 13: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.global:type_name -> kratos.api.Global
	4,  // 3: kratos.api.Bootstrap.log:type_name -> kratos.api.Log
	5,  // 4: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	6,  // 5: kratos.api.Server.asynq:type_name -> kratos.api.Server.Asynq
	8,  // 6: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	9,  // 7: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	8,  // 8: kratos.api.Data.database_list:type_name -> kratos.api.Data.Database
	9,  // 9: kratos.api.Data.redis_list:type_name -> kratos.api.Data.Redis
	10, // 10: kratos.api.Global.rsa:type_name -> kratos.api.Global.RSA
	11, // 11: kratos.api.Global.game:type_name -> kratos.api.Global.Game
	13, // 12: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	7,  // 13: kratos.api.Server.Asynq.subscriber:type_name -> kratos.api.Server.Asynq.Subscriber
	12, // 14: kratos.api.Global.Game.plaza:type_name -> kratos.api.Global.Game.Plaza
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
