// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package basic

const TableNameBaseRoleMenuRel = "basic_role_menu_rel"

// BasicRoleMenuRel mapped from table <base_role_menu_rel>
type BasicRoleMenuRel struct {
	RoleID int32 `gorm:"column:role_id;type:integer;primaryKey;comment:角色ID" json:"role_id"` // 角色ID
	MenuID int32 `gorm:"column:menu_id;type:integer;primaryKey;comment:菜单ID" json:"menu_id"` // 菜单ID
}

// TableName BasicRoleMenuRel's table name
func (*BasicRoleMenuRel) TableName() string {
	return TableNameBaseRoleMenuRel
}
