// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"battle-tiles/internal/biz"
	"battle-tiles/internal/conf"
	"battle-tiles/internal/dal/repo"
	"battle-tiles/internal/dal/repo/cloud"
	"battle-tiles/internal/infra"
	"battle-tiles/internal/infra/plaza"
	"battle-tiles/internal/server"
	"battle-tiles/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(global *conf.Global, confServer *conf.Server, data *conf.Data, confLog *conf.Log, logger log.Logger) (*kratos.App, func(), error) {
	client := infra.NewRedis(data)
	db := infra.NewPSQL(data, confLog)
	v := infra.NewDBMap(data, confLog, logger)
	v2, err := infra.NewRdbMap(data, logger)
	if err != nil {
		return nil, nil, err
	}
	manager := plaza.NewManager(global, logger)
	infraData, cleanup, err := infra.NewData(data, logger, client, db, v, v2, manager)
	if err != nil {
		return nil, nil, err
	}
	asyNQRepo := repo.NewAsyNQRepo(infraData, logger)
	asyNQUseCase := biz.NewAsyNQUseCase(asyNQRepo, logger)
	basePlatformRepo, err := cloud.NewBasePlatformRepo(infraData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	asyNQService := service.NewAsyNQService(logger, asyNQUseCase, basePlatformRepo)
	asynqServer, err := server.NewAsyNQServer(confServer, logger, asyNQService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, asynqServer)
	return app, func() {
		cleanup()
	}, nil
}
