// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	basic2 "battle-tiles/internal/biz/basic"
	cloud2 "battle-tiles/internal/biz/cloud"
	game2 "battle-tiles/internal/biz/game"
	"battle-tiles/internal/conf"
	"battle-tiles/internal/dal/repo/basic"
	"battle-tiles/internal/dal/repo/cloud"
	"battle-tiles/internal/dal/repo/game"
	"battle-tiles/internal/dal/repo/rbac"
	"battle-tiles/internal/infra"
	"battle-tiles/internal/infra/plaza"
	"battle-tiles/internal/router"
	"battle-tiles/internal/server"
	"battle-tiles/internal/service"
	basic3 "battle-tiles/internal/service/basic"
	game3 "battle-tiles/internal/service/game"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(global *conf.Global, confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := infra.NewRedis(data)
	db := infra.NewPSQL(data)
	v := infra.NewDBMap(data, logger)
	v2, err := infra.NewRdbMap(data, logger)
	if err != nil {
		return nil, nil, err
	}
	manager := plaza.NewManager(global, logger)
	infraData, cleanup, err := infra.NewData(data, logger, client, db, v, v2, manager)
	if err != nil {
		return nil, nil, err
	}
	basicUserRepo := basic.NewBasicUseRepo(infraData, logger)
	basicUserUseCase := basic2.NewBasicUserUseCase(basicUserRepo, logger)
	store := rbac.NewStore(infraData, logger)
	basicUserService := basic3.NewBasicUserService(basicUserUseCase, store)
	basicLoginRepo := basic.NewBasicLoginRepo(infraData, logger)
	authRepo := basic.NewAuthRepo(infraData, logger)
	gameAccountRepo := game.NewGameAccountRepo(infraData, logger)
	gameCtrlAccountRepo := game.NewCtrlAccountRepo(infraData, logger)
	gameAccountHouseRepo := game.NewGameAccountHouseRepo(infraData, logger)
	sessionRepo := game.NewSessionRepo(infraData)
	gameAccountUseCase := game2.NewGameAccountUseCase(gameAccountRepo, gameCtrlAccountRepo, gameAccountHouseRepo, sessionRepo, manager, logger)
	basicLoginUseCase := basic2.NewBasicLoginUseCase(basicLoginRepo, global, authRepo, gameAccountUseCase, logger)
	basicLoginService := basic3.NewBasicLoginService(basicLoginUseCase)
	basicMenuRepo := basic.NewBaseMenuRepo(infraData, logger)
	baseRoleMenuRelRepo := basic.NewBaseRoleMenuRelRepo(infraData, logger)
	baseRoleMenuBtnRelRepo := basic.NewBaseRoleMenuBtnRelRepo(infraData, logger)
	basicMenuUseCase := basic2.NewBasicMenuUseCase(global, basicMenuRepo, baseRoleMenuRelRepo, authRepo, baseRoleMenuBtnRelRepo, logger)
	basicMenuService := basic3.NewBasicMenuService(basicMenuUseCase, logger)
	basicRoleService := basic3.NewBasicRoleService(infraData)
	permissionRepo := basic.NewPermissionRepo(infraData, logger)
	basicPermissionService := basic3.NewBasicPermissionService(permissionRepo)
	basicRouter := router.NewBasicRouter(basicUserService, basicLoginService, basicMenuService, basicRoleService, basicPermissionService)
	accountService := game3.NewAccountService(gameAccountUseCase)
	gameCtrlAccountHouseRepo := game.NewCtrlAccountHouseRepo(infraData, logger)
	battleRecordRepo := game.NewBattleRecordRepo(infraData, logger)
	battleSyncManager := game2.NewBattleSyncManager(battleRecordRepo, infraData, logger)
	ctrlSessionUseCase := game2.NewCtrlSessionUseCase(gameCtrlAccountRepo, gameCtrlAccountHouseRepo, sessionRepo, manager, battleSyncManager, logger)
	sessionService := game3.NewSessionService(ctrlSessionUseCase)
	walletRepo := game.NewWalletRepo(infraData, logger)
	walletReadRepo := game.NewWalletReadRepo(infraData, logger)
	fundsUseCase := game2.NewFundsUseCase(walletRepo, walletReadRepo)
	fundsService := game3.NewFundsService(fundsUseCase, manager)
	ctrlAccountUseCase := game2.NewCtrlAccountUseCase(gameCtrlAccountRepo, gameCtrlAccountHouseRepo, gameAccountRepo, manager, logger)
	ctrlAccountService := game3.NewCtrlAccountService(ctrlAccountUseCase)
	gameShopAdminRepo := game.NewShopAdminRepo(infraData, logger)
	shopGroupRepo := game.NewShopGroupRepo(infraData, logger)
	shopAdminUseCase := game2.NewShopAdminUseCase(gameShopAdminRepo, shopGroupRepo, basicUserRepo, authRepo, logger)
	shopAdminService := game3.NewShopAdminService(shopAdminUseCase, basicUserRepo)
	shopTableService := game3.NewShopTableService(manager)
	memberRuleRepo := game.NewMemberRuleRepo(infraData, logger)
	memberRuleUseCase := game2.NewMemberRuleUseCase(memberRuleRepo, logger)
	userApplicationRepo := game.NewUserApplicationRepo(infraData, logger)
	gameShopMemberService := game3.NewGameShopMemberService(manager, memberRuleUseCase, gameShopAdminRepo, basicUserRepo, userApplicationRepo)
	gameStatsRepo := game.NewStatsRepo(infraData, logger)
	gameStatsUseCase := game2.NewGameStatsUseCase(gameStatsRepo, logger)
	gameStatsService := game3.NewGameStatsService(gameStatsUseCase, shopAdminUseCase, manager)
	walletQueryService := game3.NewWalletQueryService(fundsUseCase)
	shopApplicationLogRepo := game.NewShopApplicationLogRepo(infraData, logger)
	gameAccountGroupRepo := game.NewGameAccountGroupRepo(infraData, logger)
	gameAccountGroupUseCase := game2.NewGameAccountGroupUseCase(gameAccountRepo, gameAccountGroupRepo, shopGroupRepo, logger)
	shopApplicationService := game3.NewShopApplicationService(manager, userApplicationRepo, basicUserRepo, authRepo, gameShopAdminRepo, shopApplicationLogRepo, gameAccountGroupUseCase)
	gameGroupService := game3.NewGameGroupService(manager)
	houseSettingsRepo := game.NewHouseSettingsRepo(infraData, logger)
	feeSettleRepo := game.NewFeeSettleRepo(infraData, logger)
	houseSettingsUseCase := game2.NewHouseSettingsUseCase(houseSettingsRepo, feeSettleRepo, logger)
	houseSettingsService := game3.NewHouseSettingsService(houseSettingsUseCase)
	gameMemberRepo := game.NewGameMemberRepo(infraData, logger)
	battleRecordUseCase := game2.NewBattleRecordUseCase(battleRecordRepo, gameCtrlAccountRepo, gameCtrlAccountHouseRepo, gameAccountRepo, gameMemberRepo, houseSettingsRepo, feeSettleRepo, logger)
	battleRecordService := game3.NewBattleRecordService(battleRecordUseCase)
	shopGroupMemberRepo := game.NewShopGroupMemberRepo(infraData, logger)
	shopGroupUseCase := game2.NewShopGroupUseCase(shopGroupRepo, shopGroupMemberRepo, gameShopAdminRepo, logger)
	shopGroupService := game3.NewShopGroupService(shopGroupUseCase, gameAccountGroupUseCase, logger)
	memberUseCase := game2.NewMemberUseCase(basicUserRepo, gameShopAdminRepo, logger)
	memberService := game3.NewMemberService(memberUseCase, logger)
	gameRouter := router.NewGameRouter(accountService, sessionService, fundsService, ctrlAccountService, shopAdminService, shopTableService, gameShopMemberService, gameStatsService, walletQueryService, shopApplicationService, gameGroupService, houseSettingsService, battleRecordService, shopGroupService, memberService)
	opsService := service.NewOpsService(manager)
	opsRouter := router.NewOpsRouter(opsService)
	basePlatformRepo, err := cloud.NewBasePlatformRepo(infraData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	platformUsecase := cloud2.NewPlatformUsecase(basePlatformRepo, logger)
	platformService := service.NewPlatformService(platformUsecase)
	rootRouter := router.NewRootRouter(basicRouter, gameRouter, opsRouter, platformService)
	ginServer := server.NewHTTPServer(confServer, logger, rootRouter, infraData)
	sessionMonitor := service.NewSessionMonitor(logger, manager, basePlatformRepo, gameCtrlAccountHouseRepo, sessionRepo, gameCtrlAccountRepo, battleSyncManager, ctrlSessionUseCase)
	transportServer := server.NewMonitorServer(sessionMonitor)
	app := newApp(logger, ginServer, transportServer)
	return app, func() {
		cleanup()
	}, nil
}
